chime-experiment/ch_pipeline

ch_pipeline/analysis/beam.py
BREAKING CHANGE: `setup` methods of `TransitRegridder` and `Truncate`
raise `caput.config.CaputConfigError` instead of deprecated
`caput.pipeline.PipelineConfigError`.
see https://github.com/radiocosmology/caput/pull/156
=> fix(beam): replace deprecated caput.pipeline.PipelineConfigError

ch_pipeline/analysis/sidereal.py, ch_pipeline/core/io.py, examples/calibration_pipeline.yaml, examples/construct_timing_correction.yaml, examples/noise_calibration.yaml, examples/test.yaml, examples/test_dataflagger.yaml
They still don't all work. For example `ch_pipeline.core.io.SaveOutput` doesn't exist.
Depends on https://github.com/radiocosmology/caput/pull/147
=> docs(examples): fix some errors in the example configs

ch_pipeline/analysis/calibration.py, ch_pipeline/core/telescope.py, ch_pipeline/processing/beam.py, ch_pipeline/processing/daily.py
- Add angpos as a keyword argument to the beam method of the CHIME telescope.
Enables evaluation of the beam along a single source track, which is required
for the beamformer.  If not provided, then it will default to the _angos
telescope attribute.
- CHIME telescope now uses fast methods for evaluating the cylinder beam that
involve cacheing pre-products in a class dictionary.  This will require the
[sf/fast-beam](https://github.com/radiocosmology/driftscan/tree/sf/fast-beam) branch of driftscan to be merged.
- Add dec_normalized config parameter to CHIME class that, if set, will
normalize the beam by its magnitude at the transit of the declination
provided. To mach CHIME calibration, the user would set this parameter
to the declination of Cyg A.
- Creates a CHIMEParameterizedBeam class …
=> feat(telescope): update beam evaluation for use in beamformer code

ch_pipeline/core/io.py
The LoadSetupFile and LoadFilesFromTag task are now
subclasses of draco.core.io.BaseLoadFiles.  This provides
these tasks with the capability to load distributed containers,
convert byte strings, and make selections along axes.
Depends on PR #135 of draco.
=> feat(io): add capabilities to file loading tasks

ch_pipeline/core/telescope.py
Based on FWHM computed from point source model (585-800 MHz), this PR revises north-south FWHM being used in the driftscan beam. Beam measurements point to a lower beam width compared to the existing beam width in driftscan. The discrepancy is larger in X pol. In order to avoid ripples in the beam, FWHM (as a function of frequency) computed for the point source model is fit with a cubic polynomial, and coefficients of the fit are provided to `fwhm_e` and `fwhm_h` functions.
Note that FWHM was optimized only in 585-800 MHz. Using it below that will result in errors due to extrapolation. 
Here is the N-S beam and FWHM comparisons between the two models:
Per frequency comparisons are here: https://bao.chimenet.ca/doc/documents/1448
=> Frequency dependent FWHMs

ch_pipeline/analysis/source_removal.py, ch_pipeline/core/containers.py
- Use new ephemeris methods for computing source positions.
- Add capability to restrict the range of hour angles covered by the source model through the min_ha and max_ha config properties.
- Allow separate masking of N-S and E-W components of the baseline.
- Change data type of the param index map of SourceModel and remove the redundant source_index dataset.
- Move calculation of the source model into the frequency and polarisation loops to reduce memory usage.
=> feat(source_removal): reduce memory usage and other improvements

ch_pipeline/analysis/flagging.py, ch_pipeline/analysis/timing.py
This is ready for review. In addition to the code changes, I want to confirm that the date range I proposed makes sense, and discuss if we want to modify the task `DataFlagger` so its default does not include flags like `needs_timing_correction`. 
```
id: None
type: needs_timing_correction
start: 2018-10-11 14:00:00+00:00
finish: 2020-03-04 01:13:01+00:00
metadata: 
{instrument: chime, user: Anja Boskovic}
```
Closes #80
=> feat(timing): ApplyTimingCorrection only to data flagged by needs_timing_correction

ch_pipeline/processing/daily.py, doc/requirements.txt
Includes:
* Only start tasks for days which actually have data available online
* Adjust the daily pipeline to process available days up until October 2020
* Queue one day every 7, and then cycle back, to prioritise collecting a wider breadth
=> Changes for rev_04

ch_pipeline/analysis/calibration.py, ch_pipeline/analysis/flagging.py, ch_pipeline/core/containers.py, ch_pipeline/core/io.py, ch_pipeline/processing/daily.py
This is a draft implementation of a container type and reader for the HFB data. To run this you'll need to use radiocosmology/caput#198
Things that work:
- Reading HFB files directly using `HFBData.from_file` including axes selections.
- Time, frequency and beam selections via the Reader. Notably the time selections will take a range of UTC times to load.
Things that don't work, or need to be tweaked:
- Compression when saving out containers.
- Distributed reading of data (this requires propagating the distributed parameters from the `_dataset_spec` into the load routines).
- Is this the right place for this code?
- Maybe match the expected Reader API a little better.
This code can be used like the following:
```python
from ch_pipeline.core import containers
fname = …
```
=> feat(containers): support HFB archive data

ch_pipeline/core/dataquery.py
Not very important, but function _force_list checks for lists by checking for __iter__ attribute. Tuples, generators, numpy ndarrays, ... all have a __iter__ attribute. Probably will never be an issue, but this change will ensure that the return is actually a list.
=> fix(dataquery): forcing a list should actually force a list

ch_pipeline/analysis/sidereal.py
This will first check,  whether sources present in ephemeris.source_dictionary are also present in ch_util.fluxcat.FluxCatalog. If present then those sources above some flux threshold will be masked prior to estimating the median/mean to remove the cross-talk (noise).
=> fix: check ephemeris sources are present in ch_util.fluxcat 

ch_pipeline/analysis/mapmaker.py
Covert the daily ch_pipeline ringmap to draco ringmap. The daily ringmap of ch_pipeline has rms axis instead of weight, so we are changing rms to weight and storing it in a new draco ringmap container.
=> convert ch_pipeline ringmap to draco ringmap container 

ch_pipeline/processing/daily.py
ThresholdVisWeight filter was updated to return a RFIMask object rather
than doing the masking in place. A separate task to apply the filter was
added.
=> fix(daily): Update pipeline config for ThresholdVisWeight changes.

ch_pipeline/analysis/flagging.py, ch_pipeline/core/containers.py, examples/test_decorr_cyl.yaml
Creates a `MaskDecorrelatedCylinder` task that can be run in the daily pipeline prior to averaging over cylinder pair to identify decorrelated cylinders.  Outputs an RFIMask that when applied to the visibility data will mask any time and frequency where a decorrelated cylinder occured.
Provides [examples/test_decorr_cyl.yaml](https://github.com/chime-experiment/ch_pipeline/compare/ss/decorrelated_cyl?expand=1#diff-bb39f099ab51a8c4870537d5a946aa5820eb9403e5c1dc0f991618b8d60d8e1c) as an example of how to run the task.
The identification is more effective if the task is provided the map between frequency bin and FPGA motherboard slot.  I have generated this map for all past data based on the `fpga-master` configuration files and saved it to …
=> feat(flagging): create task for masking decorrelated cylinders

ch_pipeline/analysis/flagging.py
- fix(MaskDecorrelatedCylinder): crash when given a subset of frequencies
- fix(MaskDecorrelatedCylinder): avoid NaN warning if entire sample is invalid
=> Fixes for MaskDecorrelatedCylinder

ch_pipeline/processing/base.py, ch_pipeline/processing/client.py
`chp` commands for checking pending and running jobs would only get jobs being run by the current user. Jobs being run by a special account, such as the chime account (which is used for daily pipeline jobs) are visible to all users but could not be fetched by `chp` commands. This change adds a user option when finding slurm jobs, and adds a `-u` option when calling `chp metrics`. This also fixes #126
=> feat(client): option to select user when getting slurm jobs

ch_pipeline/core/io.py
This is ready for review.
Changes `core.io.LoadDataFiles` to load HFB data.
Selections in e.g. beam number or frequency index can be achieved as documented in `draco.core.io.BaseLoadFiles`.
=> feat(io): Load HFB data with selections

ch_pipeline/processing/base.py, ch_pipeline/processing/client.py
With the fragmented methods for getting running, pending, crashed, etc..., multiple slurm calls were required in order to get a full suite of status items (as needed for chp metrics). This method returns a dict with all status items, meaning that it should run faster
=> feat(base): method to get all job tag status items.

ch_pipeline/core/containers.py
This fixes the issues causing the build-docs check to fail in recent PRs. These numpy types were just aliases for the built-ins, so nothing changes with the behaviour.
=> fix(containers): replace some deprecated numpy types with built-ins

ch_pipeline/core/containers.py
Returning the centres of the time bins, rather than the lower edge that `ctime` gives.
=> feat(containers): add time property to RawContainer

ch_pipeline/core/io.py, ch_pipeline/hfb/__init__.py, ch_pipeline/hfb/io.py
Allows selection of
- frequency indices based on physical frequency, and of
- beam numbers based on source declination.
The task works like this in the config file:
```
-   type:       ch_pipeline.hfb.io.LoadHFBDataFiles
requires:   qfilelist
out:        tstream
params:
source_dec: -1.98729406393
freq_physical: [467.336]
```
To select multiple frequency bins, multiple physical frequencies can be added to the list: the bins in which these frequencies fall will be added. Maybe it would be good to add a way to specify a range of physical frequencies to select. What do you think?
The task also accepts manual selection of indices, like this:
```
-   type:       ch_pipeline.hfb.io.LoadHFBDataFiles
requires:   qfilelist
out:        tstream
params:
selections:
freq_range: [851, 853]
beam_range: …
```
=> HFB data loader with selections

ch_pipeline/hfb/analysis.py, ch_pipeline/hfb/io.py
Small fix to make selecting frequencies (during data loading) more robust.
Also add some comments to the docstring to explain when selections don't work: using both `beam_ew_include` and `freq_phys_list`, with both having a length > 1, yields
```
TypeError: Only one indexing vector or array is currently allowed for fancy indexing
```
=> HFB data loading frequency selection fix

ch_pipeline/processing/base.py, ch_pipeline/processing/daily.py
Adds a config option to check `n` recent days since the current CSD and process those days before others in the queue.
Also, fix a bug so the daily config can actually handle not being provided an end date for some CSD range. In this case, any data between `start` and the current CSD will be included in the queue. 
The idea here is that a daily pipeline revision can process the most recent days first as their data become available. Note that I've set the default config num days to zero, so it won't check for recent days by default.
=> Add config option to prioritize processing recent CSDs 

ch_pipeline/hfb/containers.py
Bug fix: `nsamples` should therefore be a dataset in the `HFBHighResSpectrum` container, because it is used by `HFBStackDays`.
=> HFB move nsamples dataset

ch_pipeline/hfb/io.py
Bug fix.
See if this is an okay way to fix this bug, or if a fix should be implemented elsewhere (`LoadFilesFromParams`, `BaseLoadFiles`)
=> HFB handle empty filelists in LoadFiles

ch_pipeline/hfb/analysis.py
Fix docstring of `HFBStackDays`: input `sdata` should be `HFBHighResSpectrum`, which has the `nsample` dataset
=> HFB docs sdata type

ch_pipeline/hfb/analysis.py
Bug: `template.hfb[:, :, :, np.newaxis]` in `HFBDivideByTemplate` gives problems, because `template.hfb` is an `MPIArray`.
For now I fixed this by using `.local_array`, but maybe there's a better way.
=> HFB template local array

ch_pipeline/hfb/analysis.py
Bug fix: `container.empty_like` should refer to `draco.core.containers.empty_like`.
=> HFB fix containers.empty_like

requirements.txt
This is a requirement for ch_pipeline that doesn't actually get installed with ch_pipeline
=> fix(build): add pytz to requirements.txt

ch_pipeline/analysis/flagging.py, ch_pipeline/core/containers.py, ch_pipeline/core/dataquery.py, ch_pipeline/processing/daily.py
Query the database for the frequency map that was active when a dataset was collected. Lookup is done by dataset_id, so older datasets which do not have a dataset_id will just use the default mapping that we assume was active at the time. 
Changes:
1.  Add a task to query the database for the frequency map corresponding to a dataset_id.
2.  Add a container type to hold a single frequency map. This does not modify the existing FrequencyMap container for backwards compatibility.
3. Modify the `MaskDecorrelatedCylinder` task to use the new container
4. Modify the daily config to use the new task(s)
Requires chime-experiment/ch_util#50
=> Frequency Map (1/2): Query database for frequency slot map

ch_pipeline/hfb/analysis.py
This is mostly a refactor of Arash's work on the `HFBSelectTransit` task, but it also makes a few changes:
- It makes the data selection more flexible: the user can specify what criteria (sensitivity, offset from transit time) to use to determine what data is selected, and what parameters (magic numbers) to use for those criteria.
- Selecting the maximum sensitivity in the main lobe of a beam is done by first selecting the main lobe and then taking the maximum of the sensitivities in that selection, rather than taking the sensitivity at the sample closest to transit. This change means the there will be slight changes in what data is selected.
Obtaining the RA and Dec from the HFB target list catalog (rather than the current manual entry) will be done in a future PR.
=> HFB select on-source and off-source data

ch_pipeline/core/telescope.py
The `beam` dataset in `HEALPixBeam` is a structured `np.dtype` that can't pass the `np.issubclass_` check. This patch extracts and checks the types of the `dtype` fields explicitly.
=> fix(telescope): include correct complex check for `HEALPixBeam`s

ch_pipeline/core/telescope.py
This seems to have been officially removed in recent versions, so it throws an attribute error in python 3.11 environments. `np.str` was already just an alias for the builtin `str` type
=> fix(telescope): remove deprecated np.str type

ch_pipeline/analysis/calibration.py, ch_pipeline/core/containers.py, ch_pipeline/core/dataquery.py
This PR does some things:
1. Ensures that `CHIMETimeStream` containers will only have datasets set in its spec, and that those datasets will be of the correct type when inheriting from `andata.CorrData` containers. This only affects the `flags/frac_rfi` dataset, which isn't use via the draco containers interface as far as I can tell. If it is needed, then a dataset_spec entry should be added for it.
2. Access `dataset_id` in unicode via a property on `CHIMETimeStream`
3. Properly call `dataset_id` wherever it's used
4. Fix a bug where `CHIMETimeStream.flags` would throw an error if certain datasets weren't present
Requires chime-experiment/ch_util#53
=> Dataset_id (2/2): Ensure CHIMETimeStream datasets are accurate and handle distributed `dataset_id`

ch_pipeline/analysis/calibration.py, ch_pipeline/analysis/source_removal.py, ch_pipeline/core/containers.py
Removes the `.time` property from `containers.CHIMETimeStream`. This property is now properly implemented in `caput.tod.TOData` and is shifted based on the `.index_attrs["time"]["alignment"]` attribute.
Related PRs:
- https://github.com/radiocosmology/draco/pull/227
- https://github.com/radiocosmology/caput/pull/234
- https://github.com/chime-experiment/ch_util/pull/52
=> Timestamp Alignment(4/4): Remove `CHIMETimeStream.time` property

ch_pipeline/processing/daily.py
Save the beamformed visibilities versus hour angle for the bright source catalog (ps_cora_10Jy) to be used for offline stability analysis.
=> feat(daily): save beamformed visibilities versus hour angle

ch_pipeline/core/dataquery.py, ch_pipeline/processing/daily.py
Daily pipeline config updates for rev_07.
Generally, this includes:
- Masking of extremely large or small weights (>1e30, <1e-30)
- ~~Generating and saving (but not applying) the sensitivity-based RFI mask~~
- Producing an additional delay-filtered ringmap
- Zipping zarr files in a background process
- Masking 3 additional rfi bands before making the delay spectrum. These bands seem to come from the stack.
- Reducing total run time
=> rev_07 config updates

ch_pipeline/processing/daily.py
Set a buffer two days back before processing a CSD to ensure that all data has been transferred to cedar. This should probably be temporary until a better way to check for available data is in place
=> fix(daily): add longer buffer to recent day list

ch_pipeline/hfb/analysis.py
Change `MakeHighFreqRes` so it works for both `HFBData` and `HFBTimeAverage`, converting them to `HFBHighResData` and `HFBHighResTimeAverage`, respectively.
This was useful for me to make pipeline instances where time-averaging happens earlier, as part of the on/off-source selection and differencing
=> feat(hfb): make `MakeHighFreqRes` more general

ch_pipeline/hfb/containers.py
PR #200 should be handled before this one.
I gathered the properties that were repeated for all HFB containers (except the `HFBRFIMask` one) into a new base HFB container class called `HFBContainer`. There was some inconsistency in the naming of the weights dataset between different containers. I tried to handle this, but wasn't sure if the existing names had a purpose or if some functionality could break because of my changes.
All HFB containers so far were subclasses of `core.containers.FreqContainer`, so I made `HFBContainer` a subclass of `FreqContainer`. However, HFB data does not necessarily need to have a frequency axis (although its primary purpose requires keeping a frequency axis). Perhaps at some point we want to make a container for light curves, integrated over frequency, or …
=> refactor(hfb): create base HFB container

ch_pipeline/hfb/analysis.py
There was a `redistribute` statement that was superfluous, I think. Without it, the task to also work for `HFBHighResRingMap`
=> fix(hfb): remove redistribute in `HFBStackDays`

doc/requirements.txt
I ran into the following error when trying to merge PR #218:
```
Sphinx version error:
The sphinx_rtd_theme extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
Error: Process completed with exit code 2.
```
The present PR allows Sphinx version 5.0
@tristpinsm do you remember the reason for excluding this version (as per your PR #100, over a year ago)?
I tested this by installing Sphinx 5.0.0 and sphinx-rtd-theme 2.0.0 and running the following from inside the main ch_pipeline directory: `sphinx-build -W -b html doc/ doc/_build/html`
That seemed to work without issues
=> Change doc requirements to allow Sphinx version 5.0

ch_pipeline/hfb/containers.py
Make a base class `HFBBeamContainer` for all HFB containers that have
that have a `beam` axis. This also has `beam_ew` and `beam_ns`
I think this code could be looked at already, ~~but merging may need to wait for PR #210 to be merged~~
Note to self: ~~after PR #210 is handled, but~~ before merging this PR, check if any changes still need to be added in `hfb/analysis.py` from commit 21a267c8 that could otherwise get lost
=> HFB add beam container

ch_pipeline/hfb/analysis.py
This will make it work for the blind-search pipeline, but it breaks the targeted pipeline. It shouldn't be hard to make it work for both pipeline versions.
Making this draft PR so we don't forget about this.
=> fix(hfb.analysis): fix shape of pfb_shape

ch_pipeline/core/dataquery.py, ch_pipeline/processing/daily.py
There have been a lot of issues with failed connections to chimedb from cedar recently. This PR adds a task to establish an initial connection with the database given some configurable timeout and number of attempts.
Depends on chime-experiment/chimedb#42 and chime-experiment/ch_util#69
=> Add a task to establish a database connection

ch_pipeline/analysis/calibration.py
There are occasionally NaN values in the raw weather data, which get mixed into the gains with interpolation. ~15 days have failed for this reason. This fix just excludes any NaNs or Infs from the weather data before interpolating
=> Exclude NaNs in weather data when interpolating

ch_pipeline/analysis/flagging.py
New pipeline task to mask time samples after rainy periods, intended to replace the usage of `rain1mm` and `rain1mm_sd` flags from the database. The task computes the accumulated rainfall N hours prior to each time sample in a timestream or sidereal stream, and sets the weights to zero if the rainfall total exceeds some threshold (in mm). The user can specify N and the threshold.
=> feat(flagging): add pipeline task for rainfall flagging

ch_pipeline/analysis/flagging.py
Adds the appropriate hooks for a time mask based on daytime and source transits.  Also adds B0329+54 to the list of sources where we should use the MAD algorithm for RFISensitivityMask.
=> feat(flagging): add chime version of RFIMaskChisqHighDelay

ch_pipeline/hfb/analysis.py, ch_pipeline/hfb/containers.py, ch_pipeline/hfb/io.py
It turned out that, in the HFB LoadFiles task, we only ever made the `beam_ew_include` attribute work in a loading mode used in the targeted pipeline (together with the `source_dec` attribute).
This PR makes it possible to use `beam_ew_include` (to select which EW beams to load) more generally and adds the attribute `beam_ns_range` (to select a range of NS beams to load).
=> feat(hfb.io): add selection of NS and EW beams

ch_pipeline/hfb/analysis.py
Bugfix: some code in `hfb.analysis` still used `.index_map["beam"]`, while we switched to using the axis `beam_ew` for RingMaps
=> fix(hfb.analysis): use beam_ew and el properties

ch_pipeline/hfb/analysis.py
=> HFB MPI fix hang on write-out

ch_pipeline/hfb/analysis.py
`SelectBeam` needs to subclass a pipeline task class, such as `task.SingleTask`
Otherwise, running the pipeline gives the following error:
```
AttributeError: type object 'SelectBeam' has no attribute '_from_config'
```
=> fix(hfb.analysis): make SelectBeam a pipeline task

.github/workflows/main.yml, ch_pipeline/analysis/flagging.py, ch_pipeline/processing/client.py, ch_pipeline/processing/daily.py, requirements.txt
- Uses the new `RFIStokesIMask` task, with significant improvements to RFI flagging
- Adds RFI flagging based on a high-delay chi-squared metric
- Adds RFI flagging based on sensitivity metric
Uses the new `SiderealRebinner` task in place of regridding, which is significantly simpler than the previous regridding task and eliminates the artifacts introduced at this stage. Also removes the `ThresholdVisWeightBaseline` task which was required to remove regridding artifacts.
The rebinning process results in a difference between the true and effective RA bin centres, so a correction is required. On the daily level, a local gradient is calculated based on a stack dataset with full sidereal and frequency coverage. This correction will be applied _after_ stacking when producing a stack from this …
=> Daily Pipeline rev_08 Config

ch_pipeline/processing/base.py
This is a fix that I intend to hot patch for the new pipeline runner. If a job failed very early, `f.seek` would not be able to return ~300 lines and would instead throw `OSError` and the cause of failure could not be determined. Also, the regex matches were not working with `MPI_ABORT` at the end, and it isn't really needed, so I removed it.
Note that this doesn't have to be done _immediately_, as it just affects the pipelines ability to re-queue jobs which have crashed
=> fix(base): improve re match on db connection error

ch_pipeline/hfb/containers.py
Added an axis for the trial widths of the absorption features that we search for.
- The axis is called `width`, hopefully that understandable enough.
- I put this at the front of the axis order.
- I left the `el` axis to be the distributed axis, since we may not search over more widths than we use nodes in a given run.
=> fix(hfb.containers): Add width axis and amplitude dataset to `HFBSearchResult`

ch_pipeline/hfb/io.py
Fixes a bug that gave this problem while loading files:
```
File "/home/lieshout/chime/code/ch_pipeline/ch_pipeline/hfb/io.py", line 372, in process
ts = self._load_filelist(filegroup["files"], time_range)
File "/home/lieshout/chime/code/ch_pipeline/ch_pipeline/hfb/io.py", line 306, in _load_filelist
if self.beam_sel:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
=> fix(hfb.io): make selections in file loader more robust

ch_pipeline/processing/base.py, ch_pipeline/processing/daily.py
Normally, the full log output is written to the `jobout.log` file. Occasionally, when a job fails because it reaches its time limit, the slurm message ("Job cancelled due to timeout") gets written to the slurm output file instead. Annoyingly, this doesn't seem to happen consistently. 
This change will check both the standard jobout file *and* the slurm output file.
Also, ensure that recent days are checked first in the `update_files` method of the daily processing. *NOTE*: this will have to be deployed if `auto-copy-to-online` script is removed @ketiltrout
=> Include slurm files in failed job check

ch_pipeline/processing/daily.py
With the last change I made, the pipeline would _only_ recall data for CSDS in the past week, which isn't what we want
=> Correctly include older days in --retrieve list

ch_pipeline/processing/client.py
These got automatically removed when adding ruff, since ruff doesn't like unused imports. However, they're actually needed to resolve the available processing types for `chp`.
=> Fix import extra processing types

ch_pipeline/processing/base.py, ch_pipeline/processing/daily.py
The part of the pipeline that checks for files to retrieve just looked at all the tags in the config and tried to fetch the upcoming ones that aren't online. The problem is that it didn't check to see if the tags it was trying to retrieve actually had _any_ data available anywhere, so it eventually gets stuck trying to request the same days over and over again, which will never end up online because there aren't any files.
This fix lets the pipeline first check whether a CSD has the minimum amount of data needed to run _anywhere_, not just on cedar_online.
=> Check for tags which do not have data available anywhere

ch_pipeline/analysis/flagging.py
Simple modification to `MaskSource` to support flagging the antipodal transit of a source.
Motivated by high-delay power from CAS_A antipode, especially in longer baselines.
=> Extend MaskSource to mask antipodal transits

ch_pipeline/analysis/beam.py
Fixes an issue where the HA coordinate of very long transits (~180 degrees) would not be properly re-centered about HA=0, causing the holography regridder (`ch_pipeline.analysis.beam.TransitRegridder`) to silently fail, returning a stream of 0s in the output. See the attached plot for an example of the old and new behavior for a long transit of Tau A (RA ~ 83) which wraps at 360 degrees.
=> fix(beam): properly re-center HA grid after unwrapping long transits

ch_pipeline/analysis/beam.py, ch_pipeline/analysis/calibration.py
This all still works as-is, but since Seth ported this function to `caput` as an `Observer` method (https://github.com/radiocosmology/caput/pull/290), let's use that directly.
=> refactor(analysis): Use `object_coords` Observer method

ch_pipeline/core/telescope.py
This is deprecated in numpy 2.0, and there's no reason to continue to use it anyway
=> Switch deprecated 'np.issubclass_' to 'issubclass'

CITATION.cff, ch_pipeline/analysis/flagging.py, ch_pipeline/core/telescope.py
* Refactor catalog-based masking code.
* Create TaperSourcePixelsFromCatalog and TaperSourceTracksFromCatalog,
which generate a smooth transition from 1 to 0 around the location
of bright soruces.
* Add ability to mask a subset of frequencies based on source redshift.
* Add support for a user-specified horizon limit.
=> feat(flagging): support for tapering maps around the location of sources

ch_pipeline/hfb/containers.py, ch_pipeline/hfb/flagging.py
- Replaced HFBDirectionalRFIMask with HFBDirectionalRFIMaskBitmap
- Updated HFBDirectionalRFIFlagging to generate and store four RFI datasets for different values of threshold in the new container above
- Refactored mask axis conversion tasks (e.g. HFBMaskConversion → HFBMaskRegridderNearest) to operate on HFBDirectionalRFIMaskBitmap
=> feat(hfb): update from HFBDirectionalRFIMask to HFBDirectionalRFIMaskBitmap
