ch_pipeline/analysis/beam.py, ch_pipeline/analysis/sidereal.py
Fix for breaking changes in ch_util.ephemeris.
chime_observer() -> chime.
=> fix(analysis.beam,analysis.sidereal): Fix chime_observer.

ch_pipeline/analysis/sidereal.py, ch_pipeline/core/dataquery.py, ch_pipeline/core/io.py
This supersedes: https://github.com/chime-experiment/ch_pipeline/pull/6
=> Dataquery and weather changes

ch_pipeline/analysis/calibration.py, ch_pipeline/core/dataquery.py, ch_pipeline/processing/beam.py, ch_pipeline/processing/daily.py, examples/calibration_pipeline.yaml, examples/construct_timing_correction.yaml
Related to: https://github.com/chime-experiment/Pipeline/issues/100
=> fix: chime_archive does not exist anymore; now reading from chime_online

ch_pipeline/core/telescope.py
This is not tested yet, but everything that is needed to do the interpolation is in. I thought I'd solicit some feedback early so we can figure out if this is how we want to move forward.
I implemented the interpolation in the `CHIMEExternalBeam` class because it sounded like that is where it would be most useful right now, but I think it would be straightforward to put it in a standalone class that could also be used by a task to produce `HEALPixBeam` containers (not sure where it would be appropriate to put such a class).
And would it be useful to cache the beam maps as they are produced, or do they only get used once?
=> [WIP] feat(core.telescope.CHIMEExternalBeam): Interpolate GridBeam.

ch_pipeline/analysis/beam.py, ch_pipeline/analysis/calibration.py, ch_pipeline/analysis/flagging.py, ch_pipeline/analysis/mapmaker.py, ch_pipeline/analysis/source_removal.py, ch_pipeline/core/telescope.py
Fixes a minor typo I found while I was adapting this code for general telescopes in driftscan
=> fix(CHIMEExternalBeam): fix typo in frequency interpolation

ch_pipeline/processing/base.py, ch_pipeline/processing/client.py
Added "chp metrics" command group and "list" command.
=> feat(client): Add "metrics" command to display pipeline info

ch_pipeline/processing/daily.py
The daily pipeline config involved three tasks which modified a product
in place and generated an identical product which is never used. This
update makes explicit use of the new product and ensures proper
connectivity between tasks.
=> refactor(daily): avoid hidden in-place modifications in pipeline config.

ch_pipeline/analysis/sidereal.py
The containers used in this module are no longer imported into `..core.containers`.
Import them from `draco.core.containers` instead.  Also fix the in-place operations
that were raising warnings from MPIArray.
=> fix(sidereal): accommodate changes to MPIArray and containers

ch_pipeline/processing/base.py, ch_pipeline/processing/daily.py
- config(daily): restore refactored second round RFI excision
- config(daily): write large outputs in zarr format
=> Update configs for rev05 run

ch_pipeline/processing/daily.py
- config(daily): fix thermal gain correction application
- config(daily): mask an extra RFI band to improve delay spectra
- config(daily): add an extra test day
- config(daily): change distribution to reduce allocation usage
=> rev06 updates

ch_pipeline/processing/base.py, ch_pipeline/processing/client.py
Clarifies the naming of some pipeline metrics.
=> feat(client): improve clarity of status metric naming

ch_pipeline/analysis/solar.py, ch_pipeline/core/containers.py, ch_pipeline/core/dataquery.py
Given how stale the `dw/sunstop` branch had become, it was easier to start with a fresh branch.  All I've done is branch from master, overwrite `anaysis.solar` with the version from `dw/sunstop`, and copy the `SunTransit` container in `core.containers` from that same branch.
=> Merge solar beam code

ch_pipeline/hfb/analysis.py, ch_pipeline/hfb/containers.py
- Task to remove `subfreq` axis, stitching together different frequency channels into one high-resolution `freq` axis.
- Set of high-frequency-resolution containers to hold resulting data.
=> HFB High frequency resolution

ch_pipeline/analysis/flagging.py
Add a time stamp to `static_rfi_mask_hook`.
`frequency_mask` in `ch_util/rfi.py `will read this timestamp for CSD-dependent static RFI flagging.
=> Reading a time stamp

ch_pipeline/processing/daily.py
Another config fix for the updated ThresholdVisWeights...
=> fix(processing): properly handle tvwb output mask

ch_pipeline/hfb/flagging.py
=> HFB fix divide by zero in RFI flagging

ch_pipeline/hfb/analysis.py, ch_pipeline/hfb/io.py
Questions:
1. What would we like the tags to look like? `20230302` or `lsd_3403`?
2. Which time should be used for calculating the LSD? The start time in the container or the mid-point (which will normally correspond to the transit time)?
=> HFB add tag and LSD to attributes

ch_pipeline/hfb/analysis.py, ch_pipeline/hfb/io.py
Needs PR #179 to be merged first.
=> HFB use catalog to get source coordinates

pyproject.toml
Adding a basic pyproject file for now. Will expand in future PRs (linting config, etc...)
=> feat(pyproject): add pyproject file

ch_pipeline/core/dataquery.py
Two quick fixes:
- dataset id has no associated frequency map (use the default frequency map)
- dataset id not found in chime database (if none of the available dataset ids are found, raise an exception)
=> fix(dataquery): handle case where no fmap is found for a given dataset_id

ch_pipeline/hfb/analysis.py
Replaces `HFBAverageOverTime` and `HFBAverageOverBeams` (which were very similar) with a general `HFBAverage` task that takes an `axis` attribute to specify over which axis to take the average. It can be expanded if we want to average over other axes (once the necessary containers are made).
=> HFB general averaging

ch_pipeline/processing/daily.py
Somehow the previous PR wouldn't reflect updates to the branch, so it's easier to just make a new one since this is minor.
Goes with radiocosmology/draco#241
Updated to include both XX and YY pol
=> feat(daily): add reduced ringmaps to daily config

ch_pipeline/hfb/analysis.py
Add a general pipeline task to take the difference of two sets of HFB data
=> feat(hfb): add HFB differencing task

ch_pipeline/hfb/analysis.py, ch_pipeline/hfb/containers.py
Make `HFBStackDays` more general so it can stack all types of HFB data containers.
=> feat(hfb): allow HFBStackDays with all data cont

ch_pipeline/hfb/analysis.py
This uses `ch_util.ephemeris.get_doppler_shifted_freq` to compute Doppler shifted frequencies and therefore depends on [ch_util PR #58](https://github.com/chime-experiment/ch_util/pull/58). That PR should be looked at first before this one.
To compute the Doppler shift, this task uses a single time per container (corresponding to a siderial day), rather than all the times found in the time axis. The time is calculated from the LSD and source RA, taken from the container attributes.
Data and weights at the Doppler shifted frequencies are evaluated using linear interpolation. I copied and adjusted `_interpolation_linear` from `ch_util.timing` to do the interpolation with handling of weights and exclusion of flagged data (points with weight = 0.0).
I changed the handling of flagged data from …
=> feat(hfb): add Doppler shift task

ch_pipeline/processing/base.py, ch_pipeline/processing/daily.py
This does 2 things:
1. Fixes an issue that would allow days inside of the buffer window to be queued by the daily pipeline
2. Properly stats files which are missing a "STATUS" file to look for the last edited time
=> Fixes for pipeline runner

ch_pipeline/hfb/pfb.py
Small fix to make HFB pipeline run.
=> fix(hfb.pfb): use invert_no_zero

ch_pipeline/core/io.py, ch_pipeline/core/telescope.py
- feat(MakeTelescope): a task to construct a telescope object directly
- feat(LoadCorrDataFiles): allow general axis selections
=> Allow selections when loading CHIME data

ch_pipeline/__init__.py, ch_pipeline/analysis/beam.py, ch_pipeline/analysis/decorrelation.py, ch_pipeline/analysis/flagging.py, ch_pipeline/analysis/solar.py, ch_pipeline/analysis/source_removal.py, ch_pipeline/analysis/timing.py, ch_pipeline/core/containers.py, ch_pipeline/core/dataquery.py, ch_pipeline/core/io.py, ch_pipeline/core/pathfinder.py, ch_pipeline/hfb/analysis.py, ch_pipeline/hfb/flagging.py, ch_pipeline/hfb/pfb.py, ch_pipeline/synthesis/timingerrors.py
A new version of `black` came out yesterday (?) and is flagging a bunch of code that was previously fine.
=> refactor: run black 24.1.1

ch_pipeline/hfb/analysis.py, ch_pipeline/hfb/containers.py
This code depends on PR #222 (HFB beam container), which seems to depend on PR #210 (regridding).
Also, the averaging task is not of much use without PR #223 (aligning EW beams)
=> HFB averaging high-res ringmaps over EW beams

ch_pipeline/hfb/analysis.py
Bugfix, there were some misplaced parentheses.
=> fix(hfb.analysis.HFBDividePFB): use isinstance

ch_pipeline/hfb/containers.py, ch_pipeline/hfb/io.py, ch_pipeline/hfb/sidereal.py
- feat(hfb.containers): use DataWeightContainer as base for generic functionality
- feat(HFBData): allow distributed load with from file. TEMPORARY
- feat(HFBSiderealRegridder): specialised HFB regridder
=> HFB regridding

ch_pipeline/processing/quarterstack.py
- feat(quarterstack): allow revisions to be judged by opinions from different revisions
- fix(quarterstack): update paths to new /project space
- feat(quarterstack): add extra RFI flagging and thresholding to processing
- refactor(quarterstack): miscellaneous cleanups
=> Quarterstack updates

ch_pipeline/processing/base.py, ch_pipeline/processing/beam.py, ch_pipeline/processing/daily.py, ch_pipeline/processing/quarterstack.py
Requires radiocosmology/caput#255
=> Include module load options and defaults

ch_pipeline/analysis/flagging.py
Based on radiocosmology/draco#265. Requires 265 to merge for tests to pass
=> Chime-specific version of new RFI mask

ch_pipeline/core/dataquery.py, ch_pipeline/processing/base.py, ch_pipeline/processing/client.py, ch_pipeline/processing/daily.py, ch_pipeline/processing/runner.py, requirements.txt
- Use Alpenhorn to manage access to nearline data when needed
- Check for heavily flagged days when creating a new revision and add a list of CSDS to exclude 
- Check for weather data when deciding on available days
- Require a minimum fraction of available data for a day to be considered available (this is set to zero by default)
- Specify a rolling window of recent days which should be prioritized by the pipeline
- These days can be given a separate fair share threshold 
- Optionally, the pipeline can **only** run these days
- Add a daemon which can run any `ProcessingType` pipeline
- NOTE: I'm not sure yet if it's worth using this for the daily pipeline, but I've found it to be very useful for testing pipeline updates on moderate chunks of days. It's also overkill for what I need it …
=> Updates to daily pipeline infrastructure

ch_pipeline/hfb/analysis.py
Add task to move samples so the RA axis is correct for all EW beams.
=> HFB align EW beams

README.md
The whole file got re-written because I changed from DOS to Unix line endings, but the only substantive change is a rewrite of the "Dependencies" section.
=> Update README.md for pyproject.toml

ch_pipeline/analysis/beam.py, ch_pipeline/analysis/calibration.py, ch_pipeline/analysis/decorrelation.py, ch_pipeline/analysis/flagging.py, ch_pipeline/analysis/fringestop.py, ch_pipeline/analysis/mapmaker.py, ch_pipeline/analysis/sidereal.py, ch_pipeline/analysis/solar.py, ch_pipeline/analysis/source_removal.py, ch_pipeline/analysis/timing.py, ch_pipeline/core/dataquery.py, ch_pipeline/core/io.py, ch_pipeline/core/telescope.py, ch_pipeline/hfb/analysis.py, ch_pipeline/hfb/io.py, ch_pipeline/hfb/sidereal.py, ch_pipeline/processing/beam.py, ch_pipeline/processing/daily.py, ch_pipeline/processing/quarterstack.py, pyproject.toml
This also resolves the use of a number of private symbols formerly imported from `ch_util.tools` which have been deleted from there.
=> fix: Use ch_ephem directly

.github/workflows/main.yml, ch_pipeline/analysis/beam.py, ch_pipeline/analysis/calibration.py, ch_pipeline/analysis/decorrelation.py, ch_pipeline/analysis/flagging.py, ch_pipeline/analysis/fringestop.py, ch_pipeline/analysis/mapmaker.py, ch_pipeline/analysis/sidereal.py, ch_pipeline/analysis/solar.py, ch_pipeline/analysis/source_removal.py, ch_pipeline/analysis/timing.py, ch_pipeline/core/containers.py, ch_pipeline/core/dataquery.py, ch_pipeline/core/io.py, ch_pipeline/core/pathfinder.py, ch_pipeline/core/telescope.py, ch_pipeline/hfb/analysis.py, ch_pipeline/hfb/containers.py, ch_pipeline/hfb/flagging.py, ch_pipeline/hfb/io.py, ch_pipeline/hfb/pfb.py, ch_pipeline/hfb/sidereal.py, ch_pipeline/processing/base.py, ch_pipeline/processing/beam.py, ch_pipeline/processing/client.py, ch_pipeline/processing/daily.py, ch_pipeline/processing/quarterstack.py, ch_pipeline/processing/runner.py, ch_pipeline/synthesis/timingerrors.py, pyproject.toml
Adding ruff linting here. See https://github.com/radiocosmology/draco/pull/243
=> Ruff linting

ch_pipeline/analysis/flagging.py, ch_pipeline/analysis/solar.py
A couple of variable names got changed.
=> Fix variable name changes in `ch_ephem`

ch_pipeline/analysis/flagging.py
This is a minor change to allow us to use `MaskDay/MaskSource` tasks directly on another mask container, without changing any other existing behaviour. Not a high priority, but something that I found useful in some testing.
=> Apply source masks to mask containers

ch_pipeline/processing/base.py
There have been a number of times where multiple jobs for the same CSD end up queued and running, which burns an excessive amount of compute resources. It seems to happen when Cedar starts to respond after being unresponsive (but not technically inaccessible) for a while.
=> Check for duplicate jobs and cancel all but one of them

ch_pipeline/hfb/containers.py, ch_pipeline/hfb/flagging.py
1) I newly defined a new function 'sensitivity_metric' to compute sensitivity metric.
2) I fixed the bug in 'HFBRadiometerRFIFlagging' and updated it to use the function above.
3) I renamed 'HFBSensitivityFlagging' to 'HFBDirectionalRFIFlagging' and updated it to use the function above.
=> Defining a function to compute sensitivity metric

ch_pipeline/hfb/containers.py
Add compression option to the frac_rfi dataset of HFBDirectionalRFIMask
=> feat(hfb/container): add compression option to HFBDirectionalRFIMask

ch_pipeline/analysis/spectral_lines.py, ch_pipeline/core/containers.py
Takes all outlier excursions in a RingMap, clusters them based on their proximity using some normalized 3D distance metric, characterizes each cluster, and populates a new SpectralLineCatalog container with the results.
=> feat(spectral_lines): task to identify candidate spectral lines
